Repository codestates/slow-postbox, pull requests merged in 2021-12, with the labels that each got.

#190 [Refactor] / #188 / 마이페이지 css 수정 및 추가
  client/src/components/FindUserInfo/ChangePassword.css
  client/src/components/MailForm/Editor.js
  client/src/components/MyPage/Withdrawal.css
  client/src/pages/MyPage.css
  client/src/pages/MyPage.js
  server/config/config.js
  server/controllers/admin/userList.js
  server/controllers/mail/receivedlogs.js
  server/controllers/mail/sentlogs.js
  server/controllers/user/auth.js
  server/controllers/user/signup.js
  server/index.js
  server/package-lock.json
  server/seed.sql
  server/uploads/CSR.png
  server/uploads/champ4-9900000000079e3c.jpg
  server/uploads/cy.jpg
  server/uploads/slowpostlogo.png
  server/uploads/undraw_Mailbox_re_dvds.png
  server/uploads/undraw_confidential_letter_w6ux (1).png
  server/uploads/unnamed (1).png
  server/uploads/원주민.png
Labels: refactor

#193 [Client] / #191 / feat: 관리자페이지, 편지쓰기, 편지함, 마이페이지 auth 인증 추가
  client/src/components/AdminPage/AdminMail.js
  client/src/components/AdminPage/AdminUser.js
  client/src/components/WholeReceiveMailBox/WholeReceivedMail.js
  client/src/components/WholeSentMail/WholeSentMail.js
  client/src/pages/AdminPage.css
  client/src/pages/AdminPage.js
  client/src/pages/Footer.js
  client/src/pages/MailForm.js
  client/src/pages/ModalLogin.css
  client/src/pages/ModalLogin.js
  client/src/pages/MyPage.js
  client/src/pages/NavigationBar.js
Labels: C: 1h

#194 [Client] / #192 / design: Home,Navigation,AdminPage 반응형 CSS 수정
  client/src/App.css
  client/src/pages/AdminPage(480px).css
  client/src/pages/AdminPage.css
  client/src/pages/Home.css
  client/src/pages/NavigationBar.css
  server/index.js
Labels: Client, Advanced, C: 1h

#195 [Refactor] / #189 / 메일작성 페이지 css 변경 및 추가
  .github/ISSUE_TEMPLATE/-------.md
  README.md
  client/package-lock.json
  client/src/actions/index.js
  client/src/components/FindUserInfo/ChangePassword.css
  client/src/components/FindUserInfo/ChangePassword.js
  client/src/components/MailForm/CompleteModal.js
  client/src/components/MailForm/MailInfo.css
  client/src/components/MailForm/MailInfo.js
  client/src/components/MailForm/PreviewModal.css
  client/src/components/WholeReceiveMailBox/Paging.js
  client/src/components/WholeSentMail/Paging.js
  client/src/pages/MailForm.css
  client/src/reducers/index.js
  client/src/reducers/mailReducer.js
  server/funcs/index.js
  server/index.js
Labels: refactor

#196 [Client/Server] / timezone 설정 , 편지함 시간설정
  client/src/components/WholeReceiveMailBox/MailView.css
  client/src/components/WholeReceiveMailBox/MailView.js
  client/src/components/WholeReceiveMailBox/ReceiveMail.css
  client/src/components/WholeReceiveMailBox/ReceiveMail.js
  client/src/components/WholeReceiveMailBox/ReservedMail.js
  client/src/components/WholeReceiveMailBox/WholeReceivedMail.css
  client/src/components/WholeReceiveMailBox/WholeReceivedMail.js
  client/src/components/WholeSentMail/ReservedSentMail.js
  client/src/components/WholeSentMail/SentMail.js
  client/src/components/WholeSentMail/WholeSentMail.js
  server/config/config.js
  server/controllers/mail/getReceive.js
  server/controllers/mail/getReserved.js
Labels: Client
