Repository codestates/slow-postbox, pull requests merged in 2022-01, with the labels that each got.

#200 [Refactor] / #198 / 마이페이지 활동로그 css 수정
  client/src/pages/MyPage.css
  client/src/pages/MyPage.js
  server/index.js
Labels: refactor

#203 [Server] / #202 / feat: 게스트 로그인 기능 서버 구현
  server/controllers/mail/getReceive.js
  server/controllers/user/auth.js
  server/controllers/user/guest.js
  server/controllers/user/index.js
  server/controllers/user/login.js
  server/controllers/user/logout.js
  server/router/userRouter.js
  server/schema.sql
  server/uploads/TIL.png
Labels: C: 2h

#204 [Server] / fix: 받은편지함/도착예정함 서버 join 버그 해결
  server/controllers/mail/getReceive.js
  server/controllers/mail/getReserved.js
Labels: C: 0.5h

#205 [Client] Fix : 반응형 웹페이지 수정 및 편지함 게스트 유저 확인 여부 추가
  client/src/components/WholeReceiveMailBox/MailView.css
  client/src/components/WholeReceiveMailBox/ReceiveMail.css
  client/src/components/WholeReceiveMailBox/ReceiveMail.js
  client/src/components/WholeReceiveMailBox/ReservedMail.js
  client/src/components/WholeReceiveMailBox/WholeReceivedMail.css
  client/src/components/WholeReceiveMailBox/WholeReceivedMail.js
  client/src/components/WholeSentMail/ReservedSentMail.js
  client/src/components/WholeSentMail/SentMail.css
  client/src/components/WholeSentMail/SentMail.js
  client/src/components/WholeSentMail/SentMailView.js
  client/src/components/WholeSentMail/WholeSentMail.js
Labels: Client

#209 [Refactor] / #208 / 마이페이지 게스트 로그인
  client/src/pages/MyPage.css
  client/src/pages/MyPage.js
Labels: refactor

#210 [Refactor] / #201 / gitbook 수정중
  client/src/pages/SignUp.js
  server/controllers/mail/check.js
  server/controllers/mail/checkedReceived.js
  server/controllers/mail/create.js
  server/controllers/mail/patchReceive.js
  server/controllers/mail/receivedlogs.js
  server/controllers/user/index.js
  server/controllers/user/info.js
  server/controllers/user/kakaowithdraw.js
  server/controllers/user/mailverify.js
  server/controllers/user/modify.js
  server/controllers/user/withdraw.js
  server/router/userRouter.js
Labels: refactor

#213 [Client] Fix: guest 받은편지함 tab 클릭제한 설정 및 보낸편지함 이용가능 수정
  client/src/components/WholeReceiveMailBox/WholeReceivedMail.css
  client/src/components/WholeReceiveMailBox/WholeReceivedMail.js
  client/src/components/WholeSentMail/WholeSentMail.js
Labels: Client

#214 [Client] / Design: 마이페이지 css 수정
  client/src/pages/MyPage.css
  client/src/pages/MyPage.js
Labels: Client

#215 [Client] / #212 / 게스트 로그인시 내게쓰기 숨기기
  client/src/components/MailForm/MailInfo.css
  client/src/components/MailForm/MailInfo.js
Labels: C: 0.5h

#217 [Refactor] / #201 / 서버 리팩토링
  client/src/App.js
  client/src/components/MyPage/Withdrawal.js
  client/src/components/SignUp/kakao.js
  client/src/pages/Login.js
  client/src/pages/MailForm.js
  client/src/pages/MyPage.js
  client/src/pages/NavigationBar.js
  client/src/pages/SignUp.js
  server/controllers/admin/mail.js
  server/controllers/admin/user.js
  server/controllers/mail/create.js
  server/controllers/mail/getReceive.js
  server/controllers/mail/getReserved.js
  server/controllers/mail/getReservedSent.js
  server/controllers/mail/getSent.js
  server/controllers/mail/index.js
  server/controllers/mail/patchReceive.js
  server/controllers/mail/patchReserved.js
  server/controllers/mail/patchSent.js
  server/controllers/mail/receivedlogs.js
  server/controllers/mail/sentlogs.js
  server/controllers/mail/viewReceive.js
  server/controllers/mail/viewSent.js
  server/controllers/user/duplication.js
  server/controllers/user/emailVerification.js
  server/controllers/user/guest.js
  server/controllers/user/index.js
  server/controllers/user/info.js
  server/controllers/user/kakaoWithdrawal.js
  server/controllers/user/login.js
  server/controllers/user/logout.js
  server/controllers/user/reservationNotice.js
  server/controllers/user/signup.js
  server/controllers/user/withdrawal.js
  server/funcs/index.js
  server/index.js
  server/router/mailRouter.js
  server/router/userRouter.js
Labels: refactor

#225 [Refactor] / #224 / 서버 리팩토링(Home, Admin 관련 API) (#224)
  client/src/App.js
  client/src/components/AdminPage/AdminMail.js
  client/src/components/AdminPage/AdminUser.js
  client/src/pages/AdminPage.js
  client/src/pages/Home.js
  client/src/pages/NavigationBar.js
  server/controllers/admin/mail.js
  server/controllers/admin/mailList.js
  server/controllers/admin/user.js
  server/controllers/admin/userList.js
  server/controllers/home/total.js
  server/index.js
  server/router/adminRouter.js
  server/router/homeRouter.js
Labels: C: 1h

#227 [Refactor] / edit: 버그수정 및 주석삭제
  client/src/components/MailForm/Editor.js
  client/src/pages/MyPage.js
  server/index.js
  server/uploads/Screenshot from 2022-01-03 23-38-01.png
  server/uploads/Screenshot from 2022-01-03 23-46-29.png
  server/uploads/Screenshot from 2022-01-03 23-49-37.png
  server/uploads/Screenshot from 2022-01-04 11-48-12.png
  server/uploads/Screenshot from 2022-01-07 21-08-31.png
  server/uploads/Screenshot from 2022-01-08 16-43-05.png
  server/uploads/Screenshot from 2022-01-12 21-02-09.png
Labels: refactor

#228 [Refactor] / 비밀번호 암호화 방식 변경
  client/src/components/FindUserInfo/ChangePassword.js
  client/src/components/FindUserInfo/ConfirmEmail.js
  client/src/pages/MailForm.js
  server/controllers/mail/index.js
  server/controllers/user/info.js
  server/controllers/user/login.js
  server/controllers/user/reservationNotice.js
  server/index.js
Labels: refactor
